#!/bin/sh
# Update local code graphs after each successful commit.

. "$(git rev-parse --show-toplevel)/.githooks/crg-hook-lib.sh"
crg_run update

. "$(git rev-parse --show-toplevel)/.githooks/codegraph-hook-lib.sh"
codegraph_run sync

